name: NetherLink
description: "Broadcast a remote server as a local server ."

publish_to: 'none'
version: 2.0.0+7

environment:
  sdk: ^3.8.1
dependencies:
  udp: ^5.0.3
  url_launcher: ^6.3.1 
  wakelock_plus: ^1.3.2
  path_provider: ^2.1.5
  http: ^1.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
